---
language: python
python: "2.7"
dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-apt aptitude

install:
  # Install ansible
  - sudo pip install ansible

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run the role/playbook with ansible-playbook.
  - sudo ansible-playbook tests/test.yml -i tests/hosts

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
